---

#####################################
# Install Cluster overprovisioner via helm
#####################################

- name: Adding Cluster overprovisioner via Helm
  shell: |
    helm install --name cluster-overprovisioner \
    stable/cluster-overprovisioner
