---

#####################################
# Install Cluster overprovisioner via helm
#####################################

- name: Set replica_count variable
  set_fact: 
    replica_count: 1
  when: replica_count is undefined or replica_count =="auto"

- name: Set utilisation_multiplier variable
  set_fact: 
    utilisation_multiplier: 0.50
  when: utilisation_multiplier is undefined or utilisation_multiplier =="auto"

- name: Set resources_requests_cpu variable
  block: 
    - ec2_instance_facts:
        region: "{{ aws_region }}"
        filters:
          "tag:Name": "nodes.{{ cluster_name }}.{{ dns_zone }}"
      register: ec2if
 
    - set_fact:
        resources_requests_cpu: "{{ ec2if.instances[0].cpu_options.core_count * ec2if.instances[0].cpu_options.threads_per_core * utilisation_multiplier }}"

  when: resources_requests_cpu is undefined or resources_requests_cpu =="auto"

- name: Adding Cluster overprovisioner via Helm
  shell: >-
    helm install --atomic --dep-up --timeout=600
    --name cluster-overprovisioner
    --namespace kube-system
    --set deployments[0].name=node
    --set deployments[0].replica_count="{{ replica_count }}"
    --set deployments[0].resources.requests.cpu="{{ resources_requests_cpu }}"
    stable/cluster-overprovisioner
  args:
    executable: /bin/bash
