---
###########################
# Setup Kubernetes Cluster
###########################

- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - import_role: 
      name: lambda-delete
    tags: [use_lambda,never]
  - import_role: 
      name: lambda-install
    tags: [use_lambda,never]
  - set_fact:
      lambda_tags: true
    tags: [use_lambda,never]
  - import_role: 
      name: create-state-store
    tags: always
  - import_role: 
      name: create-cluster
    tags: always
  - import_role:
      name: helm-install
    tags: always
  - import_role:
      name: helm-metrics-server
    tags: always
  - import_role:
      name: helm-cluster-autoscaler
    tags: always
  - import_role:
      name: helm-cluster-overprovisioner
    tags: always
  - import_role:
      name: helm-k8s-spot-termination-handler
    tags: always
  - import_role:
      name: helm-nginx-ingress
    tags: always
  - import_role:
      name: kubernetes-dashboard
    tags: never
