---
#########################
# Install Default Ingress
#########################

- hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - import_role:
        name: helm-nginx-ingress
      vars:
        k8s_namespace: default
        load_balancer_source_ranges:
          - 62.30.202.70/32
          - 81.133.235.205/32

    - import_role:
        name: hello-kubernetes
      vars:
        k8s_namespace: default
