---
#########################
# Install Default Ingress
#########################

- hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - import_role:
        name: helm-nginx-ingress
      vars:
        k8s_namespace: default
        use_default_backend: true
        backend_protocol: http
        use_ssl: true
        ssl_ports: https
        target_ports_http: http
        target_ports_https: https
