---

############################################
# Delete the Kubernetes cluster
############################################

- hosts: localhost
  gather_facts: no
  connection: local
  roles:
    - create-state-store
#    - lambda-delete
    - delete-cluster
    - delete-state-store

  tasks:
    - file:
        path: "{{ '~/.kube' | expanduser }}"
        state: absent
