---

############################################
# Delete the Kubernetes cluster
############################################

- hosts: localhost
  gather_facts: no
  connection: local
  roles:
    - lambda-delete
    - delete-cluster
    - delete-state-store
