---
# K8S Settings
k8s_namespace: default

# EFS Settings
efs_name_tag: "{{ cluster_name }}.{{ dns_zone }}"

# VPC Data
subnet_ids: []

# Manifest vairables to change
search_and_replace:
  file.system.id:
    find: "yourEFSsystemid"
    replace: ""
  aws.region:
    find: "regionyourEFSisin"
    replace: "{{ aws_region }}"
  provisioner.name:
    find: "example.com/aws-efs"
    replace: "{{ efs_name_tag }}/aws-efs"
  server:
    find: "yourEFSsystemID.efs.yourEFSregion.amazonaws.com"
    replace: ""
  provisioner:
    find: "example.com/aws-efs"
    replace: "{{ efs_name_tag }}/aws-efs"
