---
# K8S Settings
k8s_namespace: default

# EFS Settings
efs_name_tag: "{{ cluster_name }}.{{ dns_zone }}"

# VPC Data
subnet_ids: []

# RBAC vairables to change
rbac_search_and_replace:
  namespace:
    value: "default"
    replace: "{{ k8s_namespace }}"

# Manifest vairables to change
manifest_search_and_replace:
  file.system.id:
    value: "yourEFSsystemid"
    replace: ""
  aws.region:
    value: "regionyourEFSisin"
    replace: "{{ aws_region }}"
  provisioner.name:
    value: "example.com/aws-efs"
    replace: "{{ efs_name_tag }}/aws-efs"
  server:
    value: "yourEFSsystemID.efs.yourEFSregion.amazonaws.com"
    replace: ""
  provisioner:
    value: "example.com/aws-efs"
    replace: "{{ efs_name_tag }}/aws-efs"
