---
# K8S Settings
k8s_namespace: kube-storage

# EFS Settings
efs_name_tag: "{{ cluster_name }}.{{ dns_zone }}"

# VPC Data
subnet_ids: []

# Config files to update
config_files_to_update:
  - "rbac"
  - "manifest"
  - "deployment"

# RBAC vairables to change
rbac_search_and_replace:
  namespace:
    find: "default"
    replace: "{{ k8s_namespace }}"

# Manifest vairables to change
manifest_search_and_replace:
  file.system.id:
    find: "yourEFSsystemid"
    replace: ""
  aws.region:
    find: "regionyourEFSisin"
    replace: "{{ aws_region }}"
  provisioner.name:
    find: "example.com/aws-efs"
    replace: "{{ efs_name_tag }}/aws-efs"
  server:
    find: "yourEFSsystemID.efs.yourEFSregion.amazonaws.com"
    replace: ""
  provisioner:
    find: "example.com/aws-efs"
    replace: "{{ efs_name_tag }}/aws-efs"

deployment_search_and_replace:
  server:
    find: "fs-47a2c22e.efs.us-west-2.amazonaws.com"
    replace: ""
