---

######################################
# Install Prometheus Operator via Helm
######################################

- name: Adding Prometheus Operator via Helm
  shell: >-
    helm install --atomic --dep-up
    --name prometheus-operator
    --namespace kube-system
    stable/prometheus-operator
  args:
    executable: /bin/bash
