---
######################################
# Install Prometheus Operator via Helm
######################################
- import_role:
    name: helm-grafana
  vars:
    k8s_namespace: "{{ k8s_namespace }}"

- import_role:
    name: helm-loki
vars:
    k8s_namespace: "{{ k8s_namespace }}"

- import_role:
    name: helm-promtail
vars:
    k8s_namespace: "{{ k8s_namespace }}"

- name: Adding Prometheus Operator via Helm
  shell: >-
    helm install --atomic --dep-up
    stable/prometheus-operator
    --name prometheus-operator
    --namespace "{{ k8s_namespace }}"
    --set coreDns.enabled=false
    --set kubeDns.enabled=true
    --set kubeProxy.enabled=false
  args:
    executable: /bin/bash
