---

######################################
# Install Prometheus Operator via Helm
######################################

- name: Adding Prometheus Operator via Helm
  shell: >-
    helm install --atomic --dep-up
    stable/prometheus-operator
    --name prometheus-operator
    --namespace monitoring
    --set coreDns.enabled=false
    --set kubeDns.enabled=true
  args:
    executable: /bin/bash
