---

####################
# Delete Kubernetes cluster using Kops
####################

- name: Delete the cluster
  shell: "kops delete cluster {{ cluster_name }}.{{ dns_zone }} --state {{ state_store }} --yes"
  args:
    executable: /bin/bash
  register: cmd_result
  until: cmd_result.rc == 0
  retries: 30
  delay: 60
