---

####################
# Delete Kubernetes cluster using Kops
####################

- name: Delete the cluster
  shell: "kops delete cluster {{ cluster_name }}.{{ dns_zone }} --state {{ state_store }} --yes"
  args:
    executable: /bin/bash
  #ignore_errors: true
