---

####################
# Delete Kubernetes cluster using Kops
####################

- name: Delete the cluster
  shell: "kops delete cluster {{ cluster_name }}.{{ dns_zone }} --state {{ state_store }} --yes"
  ignore_errors: true
