---
## Cluster details
dns_zone: eu-west-1.brainomix.com
#dns_zone: rs.brainomix.com
cluster_name: k8s

## Where to store cluster state
state_store: "s3://{{ cluster_name }}.{{ dns_zone }}"

## Which Kubernetes to install
# The verison of K8S you select has to be older 
# than the current kops version installed.
# If you want the latest supported, leave this on 'auto'.
k8s_version: auto

## Remote access
ssh_public_key: ~/.ssh/id_rsa.pub
ssh_access_cidr:
  - 80.6.82.34/32
  - 62.30.202.70/32
  - 81.133.235.205/32

## AWS Region to use
### London
#aws_region: "eu-west-2"
### Ireland
aws_region: "eu-west-1"

## Availability zones to use
# Select individual zones or to use ALL 
# zones leave this as 'auto'.
#aws_zones: eu-west-2a #, eu-west-2b, eu-west-2c
aws_zones: auto

## Network
#network_cidr: 10.10.0.0/16
network_cidr: auto
kubernetes_networking: calico

# Topology must be either public or private
topology: private
bastion: false

# API Access to be either public or private
api_loadbalancer_type: public
api_access_cidr: "{{ ssh_access_cidr }}"

## EC2 host details
# The instances base_image has to be specific to the aws_region you plan to use.
#base_image: 595879546273/CoreOS-stable-2191.5.0-hvm
base_image: auto

## Master configuration
# Use master_zones if you want your masters in different zones than worker nodes.
# Useful especially when you want 1 master in single zone but workers in several zones.
# When not defined, aws_zones will be used instead
#master_zones: "eu-west-2a"
master_zones: auto
# What size instance to create
master_size: t3a.small
#master_size: auto
# How many instances to create
# This has to be > master_zones count or will be set to = master_zones count.
master_count: auto
# Use master_max_price if you want to use spot instances.
# Useful to reduce cost during testing
#master_max_price: 0.05
# Use master_profile if you want custom iam policies
#master_profile: arn:aws:iam::1234567890108:instance-profile/kops-custom-master-role

## Node configuration
node_size: t3a.medium
node_count: auto
# Use node_max_price if you want to use spot instances.
# Useful to reduce cost during testing
#node_max_price: 0.05
# Define min/max node counts for the Auto Scaling Group in AWS.
node_autoscaler_min: 1
node_autoscaler_max: 3
# Use node_profile if you want custom iam policies
#node_profile: arn:aws:iam::1234567890108:instance-profile/kops-custom-node-role

## Tags
tag_creator: CreatorTag
tag_owner: OwnerTag
tag_application: AppTag
tag_costcenter: CostCenterTag
tag_product: ProductTag
tag_confidentiality: ConfidentialityTag
tag_environment: EnvironmentTag

## IAM
iam:
  allow_container_registry: false

## Cluster Overprovision
replica_count: 1
utilisation_multiplier: 0.5
