kind: Service apiVersion: v1 metadata:
  name: brainomix-production-website
  namespace: default
  selfLink: /api/v1/namespaces/default/services/brainomix-production-website
  uid: 1785202d-f1b5-11e9-8605-0288e659bc36
  resourceVersion: '1530489'
  creationTimestamp: '2019-10-18T14:39:29Z'
  labels:
    run: brainomix-production-website spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8000
  selector:
    run: brainomix-production-website
  clusterIP: 100.69.246.206
  type: ClusterIP
  sessionAffinity: None status:
  loadBalancer: {}
