---

#####################################
# Install Cluster Autoscaler via Helm
#####################################

- name: "Update role/nodes.{{ cluster_name }}"
  iam_policy:
    iam_type: role
    iam_name: "nodes.{{ cluster_name }}"
    policy_name: "ec2ClusterAutoscale"
    state: present
    policy_json: " {{ lookup( 'template', 'cluster-autoscale.json.j2') }}"

- name: Wait for policy to be applied.
  iam_role_facts:
    name: "nodes.{{ cluster_name }}"
  register: result
  until: result.iam_roles[0].inline_policies | length > 1
  retries: 30
  delay: 60

- name: Adding Cluster Autoscaller via Helm
  shell: |
    helm install --name cluster-autoscaler \
    --namespace kube-system \
    --set autoDiscovery.clusterName=k8s.rs.brainomix.com \
    --set extraArgs.balance-similar-node-groups=true \
    --set awsRegion="${REGION}" \
    --set rbac.create=true \
    --set rbac.pspEnabled=true \
    --set cloudProvider=aws \
    stable/cluster-autoscaler

- name: "Update ASG to {{ node_autoscaler_min }}:{{ node_autoscaler_max }} Nodes"
  ec2_asg:
    name: "nodes.{{ cluster_name }}"
    min_size: "{{ node_autoscaler_min }}"
    max_size: "{{ node_autoscaler_max }}"
