---

#####################################
# Install Cluster Autoscaler via Helm
#####################################

- name: "Update role/nodes.{{ cluster_name }}.{{ dns_zone }}"
  iam_policy:
    iam_type: role
    iam_name: "nodes.{{ cluster_name }}.{{ dns_zone }}"
    policy_name: "ec2ClusterAutoscale"
    state: present
    policy_json: " {{ lookup( 'template', 'cluster-autoscale.json.j2') }}"

- name: Wait for policy to be applied.
  iam_role_facts:
    name: "nodes.{{ cluster_name }}.{{ dns_zone }}"
  register: result
  until: result.iam_roles[0].inline_policies | length > 1
  retries: 30
  delay: 60

- name: Set a default scale-down-unneeded-time value
  set_fact:
    scale_down_unneeded_time: "5m"
  when: scale_down_unneeded_time is undefined

- name: Adding Cluster Autoscaller via Helm
  shell: |
    helm install --atomic --dep-up \
    --name cluster-autoscaler \
    --namespace kube-system-cluster \
    --set autoDiscovery.clusterName=k8s.rs.brainomix.com \
    --set extraArgs.balance-similar-node-groups=true \
    --set extraArgs.scale-down-unneeded-time="{{ scale_down_unneeded_time }}" \
    --set extraArgs.expendable-pods-priority-cutoff="{{ expendable_pods_priority_cutoff }}" \
    --set awsRegion="{{ aws_region }}" \
    --set rbac.create=true \
    --set rbac.pspEnabled=true \
    --set cloudProvider=aws \
    stable/cluster-autoscaler

- name: Configure node count variable
  set_fact:
    node_count: 1
  when: node_count is undefined or node_count == "auto"

- name: Check we have defined a Minimum ASG Node count
  set_fact:
    node_autoscaler_min: "{{ node_count }}"
  when: node_autoscaler_min is not defined or ( node_count is defined and node_autoscaler_min is defined and node_autoscaler_min < node_count )

- name: "See how many instances are pending/running in {{ aws_region }}"
  ec2_instance_facts:
    region: "{{ aws_region }}"
    filters:
      instance-state-name: [ "pending", "running" ]
  register: eif

- name: Adjust max_instances to take into account pending/running instances.
  set_fact:
    max_instances: "{{ ( max_instances | int ) - (  eif.instances | length ) }}"

- name: Check we have a valid Maximum ASG Node count setting
  set_fact:
    node_autoscaler_max: "{{ ( max_instances | int ) }}"
  when: node_autoscaler_max is not defined or ( node_autoscaler_max > max_instances or node_autoscaler_max < node_autoscaler_min )

- name: "Update ASG to {{ node_autoscaler_min }}:{{ node_autoscaler_max }} Nodes"
  ec2_asg:
    region: "{{ aws_region }}"
    name: "nodes.{{ cluster_name }}.{{ dns_zone }}"
    min_size: "{{ node_autoscaler_min }}"
    max_size: "{{ node_autoscaler_max }}"
