---

####################
# Install Helm
####################

- name: "Create 'tiller' Service Account"
  shell: >
    {{ item }}
  args:
    executable: /bin/bash
  with_items:
    - "kubectl -n kube-system create serviceaccount tiller"
    - "kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller"

- name: Install Helm
  shell: >
    helm init --service-account tiller --history-max 200
  args:
    executable: /bin/bash

- name: Waiting for Helm to start
  shell: >
    helm version
  args:
    executable: /bin/bash
  ignore_errors: true
  register: cmd_result
  until: cmd_result.rc == 0
  retries: 30
  delay: 60

- name: "Add some Chart Repositories"
  shell: >
    helm repo add {{ item.name }} {{ item.url }}
  args:
    executable: /bin/bash
  with_items:
    - { name: "appscode", url: "https://charts.appscode.com/stable/" }
    - { name: "bitnami",  url: "https://charts.bitnami.com/bitnami" }
    - { name: "jetstack", url: "https://charts.jetstack.io" }
    - { name: "kiwigrid", url: "https://kiwigrid.github.io" }
    - { name: "loki",     url: "https://grafana.github.io/loki/charts" }

- name: "Updating Helm repo's"
  shell: >
    helm repo update
  args:
    executable: /bin/bash

