---
################################
# Install Nginx-Ingress via Helm
################################

- name: Setup Hello-Kubernetes App
  shell: |
    cat <<EOF | kubectl apply -f -
    {{ lookup( 'template', '{{ item }}') | trim }}
    EOF
  args:
    executable: /bin/bash
#  shell: |
#    kubectl apply -f {{ role_path }}/templates/{{ item }}
#  args:
#    executable: /bin/bash
  with_items:
    - "deployment.yaml.j2"
    - "service.yaml.j2"
    - "ingress.yaml.j2"
