---
k8s_namespace: default
ssl_cert_fqdn: "*.{{ dns_zone }}"
use_ssl: true
elb_type: classic
backend_protocol: http
ssl_ports: https
target_ports_http: http
target_ports_https: http
use_default_backend: false
load_balancer_source_ranges:
  - 0.0.0.0/0
use_proxy_protocol: false
