---
k8s_namespace: default
use_ssl: true
elb_type: classic
backend_protocol: http
ssl_ports: https
target_ports_http: http
target_ports_https: http
use_default_backend: true
load_balancer_source_ranges:
  - 0.0.0.0/0
