---
##################################
# Install EFS Provisioner via Helm
##################################


#- aws_kms_info:
#    region: "{{ aws_region }}"
#  register: aws_kms_state

#- debug:
#    var: aws_kms_state['keys'][0].key_arn

- name: "Collecing VPC subnets"
  ec2_vpc_subnet_info:
    filters:
      "tag:KubernetesCluster": "{{ cluster_name }}.{{ dns_zone }}"
      "tag:SubnetType": "Private"     
  register: subnet_info

- ec2_group_info:
    filters:
      group-name: "nodes.{{ cluster_name }}.{{ dns_zone }}"
  register: ec2_security_groups

- set_fact:
    nodes_security_group: "{{ ec2_security_groups['security_groups'][0].group_id }}"

- name: Populating targets list
  set_fact:
    targets: "{{ targets | default([]) }} + {{ [ { 'subnet_id': item, 'security_groups': [ nodes_security_group ] } ] }}"
  loop: "{{ subnet_info.subnets|map(attribute='id')|list }}"

- name: Creating Elastic File System
  efs:
    state: present
    name: "{{ efs_name_tag }}"
    encrypt: yes
    #kms_key_id: "{{ kms_key_id }}"
    tags:
      Name: "{{ efs_name_tag }}"
    targets: "{{ targets }}"
  register: efs_state

- set_fact:
    file_system_id: "{{ efs_state['efs'].file_system_id }}"
  when: efs_state.changed

- name: Adding EFS Provisioner via Helm
  shell: >-
    helm install --atomic --dep-up
    stable/efs-provisioner 
    --namespace {{ k8s_namespace }}
    --set efsProvisioner.efsFileSystemId={{ file_system_id }}
    --set efsProvisioner.awsRegion={{ aws_region }}
  when: efs_state.changed
