---

#################################
# Install Metrics Server via Helm
#################################

- name: Adding Metrics-Server via Helm
  shell: |
    helm install --atomic --dep-up \
    --name metrics-server \
    --set rbac.create=true \
    --set args[0]="--kubelet-insecure-tls=true" \
    --set args[1]="--kubelet-preferred-address-types=InternalIP" \
    --set args[2]="--v=4" \
    stable/metrics-server
  args:
    executable: /bin/bash

- name: "Waiting for the Metrics Server be ready."
  shell: kubectl get --raw "/apis/metrics.k8s.io/v1beta1/nodes"
  args:
    executable: /bin/bash
  ignore_errors: true
  register: cmd_result
  until: cmd_result.rc == 0
  retries: 5
  delay: 60
