---

##############################
# Configure kubectl using kops
##############################

- name: Configure kubectl using kops
  shell: >-
    kops export kubecfg --name {{ cluster_name }}.{{ dns_zone }} --state {{ state_store }}
  args:
    executable: /bin/bash
