---

#####################################
# Install Grafana via Helm
#####################################

- name: Adding Grafana via Helm
  shell: |
    helm install --atomic --dep-up \
    --name grafana \
    --set ingress.enabled=true \
    --set ingress.hosts[0]="grafana.{{ dns_zone }}" \
    --set ingress.annotations."kubernetes\.io/ingress\.class=nginx" \
    stable/grafana
  args:
    executable: /bin/bash

- route53_zone:
    zone: "{{ dns_zone }}"
  register: output

- set_fact:
    zone_id: "{{ output.result.zone_id }}"

- shell: |
    kubectl get svc nginx-ingress-controller -o jsonpath="{.status.loadBalancer.ingress[0].hostname}"
  args:
    executable: /bin/bash
  ignore_errors: true
  register: cmd_result
  until: cmd_result.rc == 0
  retries: 30
  delay: 60

- set_fact:
    elb_fqdn: "{{ cmd_result.stdout }}"

- action:
    module: ec2_elb_facts
  register: elb_facts

- set_fact:
    elb_hosted_zone_id: "{{ elb_facts | json_query(query) | join }}"
  vars:
    query:  "elbs[?dns_name=='{{ elb_fqdn }}'].hosted_zone_id"

- route53:
    command: create
    zone: "{{ dns_zone }}"
    record: "grafana.{{ dns_zone }}"
    type: A
    value: "{{ elb_fqdn }}"
    overwrite: yes
    alias: True
    alias_hosted_zone_id: "{{ elb_hosted_zone_id }}"
