---

#####################################
# Install Grafana via Helm
#####################################

- name: Adding Grafana via Helm
  shell: >
    helm install --atomic --dep-up
    --name grafana
    --namespace grafana
    --set ingress.enabled=true
    --set ingress.hosts[0]="grafana.{{ dns_zone }}"
    --set ingress.annotations."kubernetes\.io/ingress\.class=nginx"
    --set ingress.path="/"
    --set ingress.annotations."nginx\.ingress\.kubernetes\.io/rewrite-target=/"
    stable/grafana
  args:
    executable: /bin/bash

- import_role:
    name: helm-nginx-ingress
  vars:
    k8s_namespace: grafana
