---

#####################################
# Install Grafana via Helm
#####################################

- import_role:
    name: helm-nginx-ingress
  vars:
    use_default_backend: false
    k8s_namespace: "{{ local_k8s_namespace }}"
#    backend_protocol: http
#    use_ssl: true
#    ssl_ports: https
#    target_ports_http: http
#    target_ports_https: https
    load_balancer_source_ranges: "{{ dashboard_access_cidr }}"
#    use_proxy_protocol: true

- name: Adding Grafana via Helm
  shell: >-
    helm install --atomic --dep-up
    --namespace {{ local_k8s_namespace }}
    stable/grafana
    --set ingress.enabled=true
    --set ingress.hosts[0]="grafana.{{ local_k8s_namespace }}.{{ dns_zone }}"
    --set ingress.annotations."{{ "kubernetes.io/ingress.class" | regex_escape() }}={{ local_k8s_namespace }}-nginx"
  args:
    executable: /bin/bash
