---

#####################################
# Install Grafana via Helm
#####################################

- import_role:
    name: helm-nginx-ingress
  vars:
    k8s_namespace: monitoring
    use_default_backend: false
#    backend_protocol: http
#    use_ssl: true
#    ssl_ports: https
#    target_ports_http: http
#    target_ports_https: https
    load_balancer_source_ranges: "{{ dashboard_access_cidr }}"
#    use_proxy_protocol: true

- name: Adding Grafana via Helm
  shell: >
    helm install --atomic --dep-up
    --name grafana
    --namespace monitoring
    --set ingress.enabled=true
    --set ingress.hosts='grafana.{{ k8s_namespace }}.{{ dns_zone }}'
    --set ingress.annotations="{{ "kubernetes.io/ingress.class" | regex_escape() }}: {{ k8s_namespace }}-nginx"
    stable/grafana
  args:
    executable: /bin/bash
  vars:
    k8s_namespace: monitoring
