---

#####################################
# Install Grafana via Helm
#####################################

- import_role:
    name: helm-nginx-ingress
  vars:
    k8s_namespace: monitoring
    use_default_backend: false
#    backend_protocol: http
#    use_ssl: true
#    ssl_ports: https
#    target_ports_http: http
#    target_ports_https: https
    load_balancer_source_ranges: "{{ dashboard_access_cidr }}"
#    use_proxy_protocol: true

- name: Adding Grafana via Helm
  shell: >-
    helm install --atomic --dep-up
    --namespace monitoring
    stable/grafana
    --set ingress.enabled=true
    --set ingress.hosts[0]="{{ grafana.{{ k8s_namespace }}.{{ dns_zone }} | regex_escape() }}"
    --set ingress.hosts.annotations[0]="{{ "kubernetes.io/ingress.class={{ k8s_namespace }}-nginx" | regex_escape() }}"
  args:
    executable: /bin/bash
  vars:
    k8s_namespace: monitoring
