---

#####################################
# Install Grafana via Helm
#####################################
- name: Adding Grafana via Helm
  shell: >-
    helm install --atomic --dep-up
    stable/grafana
    --namespace {{ k8s_namespace }}
  args:
    executable: /bin/bash
