---

#####################################
# Install Grafana via Helm
#####################################

- name: Adding Grafana via Helm
  shell: |
    helm install --atomic --dep-up \
    --name grafana \
    --namespace kube-system \
    --set service.type=LoadBalancer \    
    stable/grafana
