---

#####################################
# Install Grafana via Helm
#####################################

- name: Adding Grafana via Helm
  shell: |
    helm install --atomic --dep-up \
    --name grafana \
    --namespace kube-system \
    stable/grafana
  args:
    executable: /bin/bash
