---

#####################################
# Install Grafana via Helm
#####################################

- name: Adding Grafana via Helm
  shell: |
    helm install --name grafana \
    --namespace kube-system \
    --service.type=LoadBalancer \    
    stable/grafana
