---

#####################################
# Install Grafana via Helm
#####################################
- import_role:
    name: helm-nginx-ingress
  vars:
    use_default_backend: true
    use_hello_kubernetes_backend: true
    load_balancer_source_ranges: "{{ dashboard_access_cidr }}"

- name: Adding Grafana via Helm
  shell: >-
    helm install --atomic --dep-up
    stable/grafana
    --namespace {{ k8s_namespace }}
    --set ingress.enabled=true
    --set ingress.hosts[0]="grafana.{{ dns_zone }}"
    --set ingress.annotations."{{ "kubernetes.io/ingress.class" | regex_escape() }}={{ k8s_namespace }}-nginx"
  args:
    executable: /bin/bash
