---

#####################################
# Install Grafana via Helm
#####################################

- name: Adding Grafana via Helm
  shell: >
    helm install --atomic --dep-up
    --name grafana
    --namespace monitoring
    stable/grafana
  args:
    executable: /bin/bash

- import_role:
    name: helm-nginx-ingress
  vars:
    k8s_namespace: monitoring
    use_default_backend: false
#    backend_protocol: http
#    use_ssl: true
#    ssl_ports: https
#    target_ports_http: http
#    target_ports_https: https
    load_balancer_source_ranges: "{{ dashboard_access_cidr }}"
#    use_proxy_protocol: true

