---

#####################################
# Install Prometheus via Helm
#####################################

- name: Adding Prometheus via Helm
  shell: |
    helm install --atomic --dep-up \
    --name prometheus \
    --namespace kube-system \
    stable/prometheus
