---

#####################################
# Install Nginx-Ingress via Helm
#####################################

- name: Adding Nginx-Ingress via Helm
  shell: |
    helm install --atomic --dep-up \
    --name nginx-ingress \
    --set controller.metrics.enabled=true \
    --set podSecurityPolicy.enabled=true \
    --set controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-type=nlb" \
    stable/nginx-ingress
  args:
    executable: /bin/bash

