---

- name: Fetch current cluster config
  shell: >-
    kops get cluster --name {{ cluster_name }}.{{ dns_zone }} -o yaml --state {{ state_store }} > /tmp/{{ cluster_name }}.{{ dns_zone }}-cluster-conf.yaml
  args:
    executable: /bin/bash
  changed_when: false

- name: Configure IAM ContainerRegistry 
  lineinfile:
    path: /tmp/{{ cluster_name }}.{{ dns_zone }}-cluster-conf.yaml
    regexp: '^(\s+)allowContainerRegistry:'
    line: '\1allowContainerRegistry: {{ iam.allow_container_registry }}'
    backrefs: yes
  when: iam.allow_container_registry is defined
  notify: 'Push cluster config'

- name: Run handlers
  meta: flush_handlers
